name: Build TinkeDSi nightly x86

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-2022

    env:
      Solution_Name: Tinke.sln

    steps:
    - uses: actions/checkout@main
    # Build
    - name: Build
      run: |
        ./compile.bat Release x86

    - uses: actions/upload-artifact@main
      with:
        name: TinkeDSi-nightly-x86
        path: build
